name = "FrequentDirections"
uuid = "6f2d2afb-1437-4c7f-80e5-60c67a0d9835"
version = "0.1.0"
authors = ["smallpondtom <tkoike45@gmail.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.12.0"
